apiVersion: v1
kind: Service
metadata:
  name: jenkins-frontend
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: jenkins
  selector:
    app: jenkins