apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
       fsGroup: 1000 
       runAsUser: 0 
      containers:
       - name: jenkins
         image: atosci/jenkinsdocker:v3
         volumeMounts:
         - mountPath: /var/jenkins_home
           name: jenkinsvolume
         ports:
         - containerPort: 8080

      volumes:
       - name: jenkinsvolume
         persistentVolumeClaim:
          claimName: jenkins-volume     