apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarq-volume-logs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi