apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi
