apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarq-volume-conf
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Mi


